### ISSUE TITLE
replace sleeps with proper wait events

### ISSUE THREAD

**Issue by neothematrix** [neothematrix/noip-renew#10]
there are a few sleeps placed in the code that allows for screenshot to be properly taken on debug level 2, this also allows some slower connection to properly run the script.
As a workaround #9 enables debug by default, but the correct solution would be to add some wait events to make sure the page is fully loaded.

**Comment by Angel0ffDeath** [comment]
I would suggest you to use explicit wait method of selenium. With this method you wait certain amount of time (let's say 5 or 10 sec) or until some given element appears. For login page the element could be login button and for confirm host page this could be the element with the expiration days. To do that you need to add the following code:

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

after driver.get add:
try:
elem = WebDriverWait(driver, 10).until(
EC.presence_of_element_located((By.XPPATH, "xpath"))
)

You should add this code after each page opening.
In the above code timeout is 10 sec (you can lower it). If element appears faster than 10 seconds of driver will not wait 10 sec, but will proceed further immediately after element appears.

**Comment by neothematrix** [comment]
thanks @Angel0ffDeath this is what I thought, we just need to find the right element for every sleep to be replaced :-)

**Comment by Angel0ffDeath** [comment]
Selenium has 2 more wait methods - Implicit Wait (you wait certain amount of time) and Fluent Wait. Fluent Wait is more advanced from explicit wait and is mainly for dynamically loaded elements, so I think explicit wait is the most appropriate. Of course you can check selenium documentation for more info :)

**Comment by Angel0ffDeath** [comment]
BTW - I also would like to suggest you all regex used to find buttons and elements to be defined as constants in the beginning of the code. This way will be very easy to find them and change them after future updates of the site....

**Comment by neothematrix** [comment]
> BTW - I also would like to suggest you all regex used to find buttons and elements to be defined as constants in the beginning of the code. This way will be very easy to find them and change them after future updates of the site....

I don't think it will be very useful anyways, all the time I had to fix the parsing I had to change the xpath, not the regular expressions, the structure of the page is usually what changes, meaning that the label you were looking for is now an attribute for example, or inside another nested table.

**Comment by Angel0ffDeath** [comment]
> > BTW - I also would like to suggest you all regex used to find buttons and elements to be defined as constants in the beginning of the code. This way will be very easy to find them and change them after future updates of the site....
> 
> I don't think it will be very useful anyways, all the time I had to fix the parsing I had to change the xpath, not the regular expressions, the structure of the page is usually what changes, meaning that the label you were looking for is now an attribute for example, or inside another nested table.

Will try to help with this... only not sure when will have enough time to do it

**Comment by Angel0ffDeath** [comment]
Partially solved in my new PR

**Comment by benyjr** [comment]
I am on vacation on the 29th, and as a result will do some testing on this submission to verify that it works.

**Comment by neothematrix** [comment]
closed by #14
