### ISSUE TITLE
autobuild and publish docker image

### ISSUE THREAD

**Issue by neothematrix** [neothematrix/noip-renew#11]
setup a pipeline that uses the Dockerfile to automatically build and publish a docker image to the docker hub

**Comment by Angel0ffDeath** [comment]
Sorry, but Im not familliar with Docker and I dont use it, but I found that:

https://docs.docker.com/docker-hub/builds/

If it helps...

**Comment by Angel0ffDeath** [comment]
It seems you are missing username and pass for the build.... Not sure. As I said Im not familiar with Docker

**Comment by Angel0ffDeath** [comment]
![image](https://user-images.githubusercontent.com/61434069/143283594-a2db5b97-47e0-4e64-961b-40301614613c.png)

**Comment by Angel0ffDeath** [comment]
![image](https://user-images.githubusercontent.com/61434069/143283689-b9999e67-714e-4aaa-a7aa-8f27c697b044.png)

**Comment by Angel0ffDeath** [comment]
As i said  - don't know....

**Comment by neothematrix** [comment]
yep I saw it, I'm also new on this integration between github and docker build, I'm testing it :)

**Comment by Angel0ffDeath** [comment]
NP. It always has first time. Nevertheless - good job. Will support you as much as I can :)

**Comment by Angel0ffDeath** [comment]
@peteakalad @benyjr Can you help with this issue???

**Comment by neothematrix** [comment]
no worries @Angel0ffDeath I think I figured out what was wrong, now the build is successful, I just need to test if it works!

**Comment by Angel0ffDeath** [comment]
Im happy for you :)

**Comment by Angel0ffDeath** [comment]
Yep. I checked - everything is ok, i.e. built. Probably you can close this issue also :)

**Comment by Angel0ffDeath** [comment]
Perfect job @neothematrix
