### ISSUE TITLE
Feedback from the script

### ISSUE THREAD

**Issue by Angel0ffDeath** [neothematrix/noip-renew#12]
The most important thing, which script doesn't do, is feedback.

Example Renew date is coming. The script executes at the right time to renew the host, but due to some reasons (change of web site, temporary no internet access during execution of the script) the host(s) was not confirmed.

In the example above, everybody would like to know the script has failed in order to reschedule for a little bit later script execution (if using home automation system) or to manually start the script. In case of using conjob an there is failure the script can be reschedule automatically for 1 hour later.

No one would like to be surprised the host has expired and deleted due to script failure....

Currently the only way to understand if everything is ok is to manually check noip web site or to manually check png files - something which is far from my understanding for automation....

Probably possible solution will be to use exit codes ( sys.exit(x) ) - x > 0 - remaining number of days (if there are more than 1 host - min value), x = 0 - everything is ok, x < 0 - script failed (and here different reasons could be assigned for no internet (-1 for instance), could not find element on the page, i.e. page changed (-2 for instance) - in this case manual intervention will be needed, but at least everybody will know that, etc....

**Comment by neothematrix** [comment]
this is a good idea, I'm not sure but you can probably already do this by checking the exit status of the script, I think if python raises an exception (that would normally happen if the website changes or the script times out) the exit code will be !=0

**Comment by peteakalad** [comment]
Can also use standard cron functionality which emails the crontab output which provides feedback if there are any problems (I use msmtp to forward mails via gmail).  Need to setup the crontab so it doesnt redirect the output to a file for it to work.  Also depends on the script properly logging out exceptions properly regarless of the log level.  Less effort than adding exit codes and adding some sort of notification mechanism.   Just another option.

Method 1 on this page seems to give good set of instructions
https://websistent.com/msmtp-cron/

**Comment by Angel0ffDeath** [comment]
@peteakalad Neothematrix uses Docker and not cronjob. I also use different way to start the script and cronjob by me doesn't work (see my answer to your comment in discussion do we need sudo)
@neothematrix The exit code from the script is always 0. All try...except... just rise an exception, but do not terminate execution of the script, which is not correct. It is stupid to try to open host renew page if login failed, but currently it tries... After login fails there should be sys.exit(-1) for instance. Nowhere in the code you will discover usage of  sys.exit().
And due to this reason I opened this issue. Currently I capture the output of the script from my automation server, but I need to write additional function to analyse this output and to take corresponding actions. It will be better if script says everything :) or at least this is the best way to do it... It is not necessary to make additional script to analyse the results from the previously running script....

**Comment by Angel0ffDeath** [comment]
@neothematrix Currently Im working on the exceptions and will propose these days a list. If we agree on the list will make corresponding changes in the code. Will not have time to test my suggestion on sleeping times replacement - from there 2 new exceptions could arise, but will include this in the list. This way we will know what exactly happens without need to watch all pictures etc... Even saving pictures could be removed :) . After everything is ok of course

**Comment by Angel0ffDeath** [comment]
Ok. According to this code;
    def run(self):
        rc = 0
        self.logger.log(f"Debug level: {self.debug}")
        try:
            self.login()
            if not self.update_hosts():
                rc = 3
        except Exception as e:
            self.logger.log(str(e))
            self.browser.save_screenshot("exception.png")
            subprocess.call(['/usr/local/bin/noip-renew-skd.sh', "*", "*", "False"])
            rc = 2
        finally:
            self.browser.quit()
        return rc

Exit codes should be 0, 2, 3. Due to this reason I always obtain exit code 0. Of course code also raises exceptions but it is not clear what code they produce (especially on different machines)

According to me the following situations need attention (negative one, 0 - for ok, and greater than zero - remaining days):

Exit codes:

Code number	|	Meaning									|	Possible cause
	>0		Expiration days
	 0		Everything is ok 
	-1		Loggin page cannot be opened or not fully loaded			NOIP server down; No Internet connection
	-2		Update hosts pae could not be loaded					NOIP server gone down; Internet connection gone down
	-3		Manual intervention required. Upgrade text detected.			I DON'T KNOW THE REASON - NEVER OCCURED
	-4		Expiration days label does not match the expected pattern in iteration	I DON'T KNOW THE REASON - NEVER OCCURED

**Comment by neothematrix** [comment]
I think it's common definition to treat as error anything different than 0 as exit code, whether it's negative or positive, so the current code seems correct to me. It's probably a bad idea using a positive exit code when the script runs properly, it might be treated as an error by some tools.

**Comment by Angel0ffDeath** [comment]
Ok. Up to you. Will do it for myself as suits me :)
