### ISSUE TITLE
Neo The Best

### ISSUE THREAD

**Issue by Angel0ffDeath** [neothematrix/noip-renew#13]
Hi all,

This time it is not a new issue, but I would like to say to @neothematrix and to all of you - good job. In the last few days the team presented here have done a lot of work (don't want to compare with other branches/forks).
Let's go further together. Personally I hope, all people here will continue to support @neothematrix

**Comment by neothematrix** [comment]
hahaha thanks @Angel0ffDeath I really appreciate it, but honestly I'm doing very little compared to what was done by the original maintainer and also you're all doing a great job!
I stopped a few minutes earlier to think about how crazy we all are, we're literally spending hours working on this small little project just to avoid a few clicks every month :-D I guess this summarize very well the concept of automation.

**Comment by Angel0ffDeath** [comment]
Yep. This is the concept of automation, and we are spending a lot of time to "work on this little project" because everybody wants the perfect result and to forget, i.e. to be sure once script is running on the right time everything is ok and it is not necessary to check it manually each month...
