### ISSUE TITLE
random timeout

### ISSUE THREAD

**Issue by neothematrix** [neothematrix/noip-renew#17]
after updating to the latest chromedriver it looks like sometimes the script is timing out for no reason with this message:

`selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from timeout: Timed out receiving message from renderer: 600.000`

**Comment by neothematrix** [comment]
disabling gpu seems to fix the issue

**Comment by peteakalad** [comment]
Still seems ok here, but not sure my chromedriver has updated, not seeing any updates with my repos.
```
$ chromedriver --version
ChromeDriver 95.0.4638.69 (6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984})
```

You disabled gpu via this addition then?

` options.add_argument("--disable-gpu")`

**Comment by neothematrix** [comment]
yes that's what I did and it seems to be running every time with no issues

`chromedriver --version 
ChromeDriver 90.0.4430.212`

I'm using a slightly older version but running inside docker, that could probably make some difference
