### ISSUE TITLE
Auto reschedule script after update

### ISSUE THREAD

**Issue by Angel0ffDeath** [neothematrix/noip-renew#18]
If you run the script as cronjob - the script runs at specified time on calculated date which is correct, confirms the host(s), but doesn't create correct new cronjob for the next run. 

Edit: Looking into the code:
        nr = min(next_renewal) - 6
        today = date.today() + timedelta(days=nr)
We always run the script 6 days before expiration date.
And if you run the script 6 days before expiration the above will result in same day. Which leads to a new cronjob after 1 year.

Possible Fix - expiration days should be reread after host is confirmed:

Existing code:
           expiration_days = self.get_host_expiration_days(host, iteration)
           next_renewal.append(expiration_days)
            self.logger.log(f"{host_name} expires in {str(expiration_days)} days")
            if expiration_days <= 7:
                self.update_host(host_button, host_name)
                count += 1

Change to:
            expiration_days = self.get_host_expiration_days(host, iteration)
            if expiration_days <= 7:
                self.update_host(host_button, host_name)
                expiration_days = self.get_host_expiration_days(host, iteration)
                next_renewal.append(expiration_days)
                self.logger.log(f"{host_name} expires in {str(expiration_days)} days")                count += 1
            else:
                next_renewal.append(expiration_days)
                self.logger.log(f"{host_name} expires in {str(expiration_days)} days")

This fix should create directly new cronjob for the correct date.

@neothematrix @benyjr @peteakalad Unfortunately will be able to test this after 1 month. If someone can test it sooner will be good...

**Comment by Angel0ffDeath** [comment]
Other possible fix is after we have confirmed at least 1 host to reread all expiration dates again...

**Comment by Angel0ffDeath** [comment]
Remark: The above bug cannot happen if you have 2 or 3 hosts with different expiration dates. But it will always happen if you have only 1 host.

**Comment by benyjr** [comment]
Unfortunately, my host updated on Dec 27th, so I will have to wait about 30 days as well, so I look forward to hearing how it goes for you.

**Comment by CrAzY-Tool** [comment]
@Angel0ffDeath 

Can you please post this Code in a Valid Code tag?
I try to test but it's not working and give a lot of errors.

**Comment by Angel0ffDeath** [comment]
`expiration_days = self.get_host_expiration_days(host, iteration)
   if expiration_days <= 7:
       self.update_host(host_button, host_name)
       expiration_days = self.get_host_expiration_days(host, iteration)
       next_renewal.append(expiration_days)
       self.logger.log(f"{host_name} expires in {str(expiration_days)} days")
       count += 1
  else:
      next_renewal.append(expiration_days)
      self.logger.log(f"{host_name} expires in {str(expiration_days)} days")`

**Comment by Angel0ffDeath** [comment]
@CrAzY-Tool Yeah... Unfortunately we should wait, but we will solve it. If something is wrong after that I will be able to test and benyjr also, so in all cases we will solve it.

**Comment by CrAzY-Tool** [comment]
Good News...Code is working perfect.
Crondate is set to correct date now.

**Comment by Angel0ffDeath** [comment]
@CrAzY-Tool ok. Thanks. Will make pull request later today
