### ISSUE TITLE
Cant connect to noip.com

### ISSUE THREAD

**Issue by alfakenzo** [neothematrix/noip-renew#25]
hi guys i found this nice script  and searched for the newest version that work. Now im here and thought 12 days last update it would work. But i get no connection to noip.com.
pi@raspberrypi:/usr/local/bin $ ./noip-renew-pi.sh
[2022/02/19 23:04:11] - Debug level: 2
[2022/02/19 23:04:11] - Opening https://www.noip.com/login...
[2022/02/19 23:04:15] - Logging in...
[2022/02/19 23:04:25] - my.noip.com page could not load

Maybe you can help to fix it again. by the way great job!

**Comment by neothematrix** [comment]
Hello!
What's the content of the exception.png and debug1.png that should have been generated with the debug level 2?
The script is working fine here.

**Comment by alfakenzo** [comment]
I don't see the debug.log. I see a lot of connections

**Comment by neothematrix** [comment]
Hi, it's not a log file you should have two png images, they are screenshots of the various pages visited by the script and should show you the actual error, you should still have them, they are creates in the same directory as the python script.
Also, make sure you're using the latest version of the script, I updated it last week for a similar login issue.

**Comment by alfakenzo** [comment]
I see only one exception.png. That should be login.
But still not connected

**Comment by neothematrix** [comment]
ok, so exception.png is showing the login page with no credential inserted?
I need some more information in order to try and understand your issue, if you manually run the script do you still get the error? are you sure your credentials are correct? Are you using the latest version of the script that I uploaded 13 days ago?

**Comment by alfakenzo** [comment]
I download now your newest version manual. Not with gut clone. And also the same no login possible.
Login is with email?

**Comment by neothematrix** [comment]
Login can be both your email or your noip username, it's the same.
Still no debug1.png has been generated? And no messages on the exception.png screenshot?

**Comment by alfakenzo** [comment]
Yes to both nothing to see

**Comment by neothematrix** [comment]
It's strange that you don't get any png, how are you executing the script?
Make sure you are running the script in a directory that is writable by the user you're running the script with, the png files will be written in the directory where you are when you run the script.
Please paste the full output, including the line showing how you're running the script, feel free to remove any sensitive info, like your username if it's printed. 
Also make sure the password you entered in the noi-renew.sh script is base64 encoded.

**Comment by CrAzY-Tool** [comment]
It's simple

`` ele_pwd.click()`` <--- This Change ist not working

**Comment by alfakenzo** [comment]
How should it be?

**Comment by neothematrix** [comment]
> It's simple
> 
> ` ele_pwd.click()` <--- This Change ist not working

what do you mean it's not working? What error do you get? it wasn't working for me the "send_keys" method so I modified it.

**Comment by neothematrix** [comment]
> How should it be? Can you make a pullrequest

no need for a pull request yet as the current version is working fine, but maybe there are other incompatibilities.
@alfakenzo please try using version 1.5.3: [here](https://github.com/neothematrix/noip-renew/releases/tag/v1.5.3) and see if it works for you.

**Comment by alfakenzo** [comment]
Ok I will try the 1.5.3

**Comment by CrAzY-Tool** [comment]
> > How should it be? Can you make a pullrequest
> 
> no need for a pull request yet as the current version is working fine, but maybe there are other incompatibilities. @alfakenzo please try using version 1.5.3: [here](https://github.com/neothematrix/noip-renew/releases/tag/v1.5.3) and see if it works for you.

No this change is not working.
It's working fine with...

```ele_pwd.send_keys(Keys.ENTER)`

**Comment by neothematrix** [comment]
@CrAzY-Tool it's working fine for me, send_keys wasn't working, it was almost always giving me a 419 page expired error (see #24).
Release 1.5.3 that I suggested to @alfakenzo is using the `send_keys(Keys.ENTER)`
Can you share what's the error you get with the new change with `click()`? I'd like to understand.
thanks!

**Comment by CrAzY-Tool** [comment]
> @CrAzY-Tool it's working fine for me, send_keys wasn't working, it was almost always giving me a 419 page expired error (see #24). Release 1.5.3 that I suggested to @alfakenzo is using the `send_keys(Keys.ENTER)` Can you share what's the error you get with the new change with `click()`? I'd like to understand. thanks!

Error > my.noip.com page could not load

**Comment by neothematrix** [comment]
> > @CrAzY-Tool it's working fine for me, send_keys wasn't working, it was almost always giving me a 419 page expired error (see #24). Release 1.5.3 that I suggested to @alfakenzo is using the `send_keys(Keys.ENTER)` Can you share what's the error you get with the new change with `click()`? I'd like to understand. thanks!
> 
> Error > my.noip.com page could not load

right, but what's the actual error shown in the debug1.png or exception.png screenshots?

**Comment by CrAzY-Tool** [comment]
Nothing.

**Comment by neothematrix** [comment]
nothing meaning?
Can you share your specs? Like what chromedriver version are you using? where are you running the script? are you using the docker image or just the script?

**Comment by CrAzY-Tool** [comment]
There are no only one Pic "exception.png"
It shows simply a the username & password but no Login to the website.

Only Script Version.

ChromeDriver 92.0.4515.98

**Comment by neothematrix** [comment]
alright thanks, I'll try to reproduce the issue!

**Comment by alfakenzo** [comment]
For me no works version 1.5.3. and got the same error like crazy-tool said. Maybe depends on Chrome version. Greets

**Comment by neothematrix** [comment]
> There are no only one Pic "exception.png" It shows simply a the username & password but no Login to the website.
> 
> Only Script Version.
> 
> ChromeDriver 92.0.4515.98

another question, what linux distro are you running the script on? debian?

**Comment by alfakenzo** [comment]
i run Raspbian on a rpi4

**Comment by neothematrix** [comment]
ok sorry guys, I'm a very bad person, I finally understood what my issue really was that was causing #24 and also why the script was working just for me with the "click()" function that it's indeed not working: I manually base64 encoded my password instead of using the setup script, and my encoded password contained a "\n" at the end that was basically already sending an "enter" to the form, for this reason, the "ENTER" function was giving me a 419, I was double sending the form!
Now that I fixed my password, indeed the "click()" function does absolutely nothing, just like it's happening to you, and reverting to the ENTER function now works flawlessly.
So, I fixed everything with the newest release 1.5.6, it should now work for everyone, sorry about that!
Please let me know if you still have issues and thanks for helping me understand this!
