### ISSUE TITLE
Docker version for raspberry

### ISSUE THREAD

**Issue by minscof** [neothematrix/noip-renew#28]
Thank you for your project.  

I would like to use it in a docker environment on a raspberry pi with buster debian.

Could you add this on docker hub ?

**Comment by neothematrix** [comment]
ciao @minscof 
I'm trying to add a build for raspi, I guess what you really need is a build for "arm" architecture of the image, that is missing.
Can you confirm the architecture of the raspberry pi? is it arm/v7?

**Comment by minscof** [comment]
Yes my raspberry architecture is arm/v7, thank you for your help

**Comment by neothematrix** [comment]
I think I managed to produce an arm/v7 version, can you try the dev image before I push it to master?
this is the dev image that should be available also for arm/v7: moebiuss/noip-renew:dev
let me know!

**Comment by neothematrix** [comment]
@minscof did you have time to check? I don't have an arm/v7 so I can't test if everything works properly.
thanks!
