### ISSUE TITLE
Error "my.noip.com page could not load"

### ISSUE THREAD

**Issue by rubenvg95** [neothematrix/noip-renew#29]
Hello!

When I run the noip-renew.sh, y always get this error after trying the login "my.noip.com page could not load"

Any solution? 

Thanks

**Comment by neothematrix** [comment]
make sure you're using the latest version of this repo.
also, if you run the script in debug mode you might be able to see the issue checking the debug*.png that are created.

**Comment by rubenvg95** [comment]
> make sure you're using the latest version of this repo. also, if you run the script in debug mode you might be able to see the issue checking the debug*.png that are created.

It's running on a raspberry pi.

Result:

`pi@raspberrypi4:~/noip-renew/noip-renew $ ./noip-renew.sh
[2022/05/24 13:13:02] - Debug level: 2
[2022/05/24 13:13:02] - Opening https://www.noip.com/login...
[2022/05/24 13:13:07] - Logging in...
[2022/05/24 13:13:27] - my.noip.com page could not load`

Credentials are OK
Git clone from today, so it's the last version

debug1.png shows the login page only (no errors on it)

**Comment by rubenvg95** [comment]
No closed, my mistake...reopen please

**Comment by neothematrix** [comment]
do you have an "exception.png"? anything useful?

**Comment by rubenvg95** [comment]
Fixed

I edit the noip-renew.py

# ele_usr.send_keys(self.username)
ele_usr.send_keys("EMAIL)
# ele_pwd.send_keys(base64.b64decode(self.password).decode('utf-8'))
ele_pwd.send_keys("PASSWORD")

Password is numbers only, probably a bug?

**Comment by neothematrix** [comment]
it's not a bug, the python script expects a base64 encoded password, setup.sh takes care of that and creates a .sh script that calls the python with the base64 encoded password.
So if you're running the python script directly, make sure you pass the password encoded in base64.

**Comment by rubenvg95** [comment]
No, I was running the ".sh" file directly, not the python file. 

Anyway, thanks a lot for your fast reply and assitance!!
