### ISSUE TITLE
Running the script on Python 3.5

### ISSUE THREAD

**Issue by Angel0ffDeath** [neothematrix/noip-renew#35]
@neothematrix It is not exactly an issue. I managed to run the script on python 3.5
The only problem in the script are f-strings which are available from python 3.6 further
So, all packages from setup.sh can be installed in python 3.5. I installed them manually
For the f-strings is necessary to additionally install:
pip3 install future-fstrings

in noip-renew.py after first row should be added:
`# -*- coding: future_fstrings -*-`

The above should be written exactly as it is!!!

Then in setup.sh I commented install, i.e:
function installer() {
  config
#install
  deploy
} 

We skip function install. WARNING: All packages from function install should be pre-installed manually.

Then run setup.sh and noip-renew-user.sh.... and amazing the script runs perfectly :)

This allows users with old systems, for instance RPi 3 with debian 9 (stretch) which is with python 3.5.3, to run the script. Installing python 3.7 on my such system didn't gave expected result and script doesnt work....

I hope this will help somebody.
@neothematrix If you want you can make a fork for python 3.5 with the above changes. Of course setup.sh can install packages automatically, just check for python 3.6 should be changed and added installation of future-fstrings

**Comment by neothematrix** [comment]
ciao @Angel0ffDeath 
can we change the setup.sh to behave differently if python 3.5 is detected? this would allow users to just use the script without any other change.
If you manage to do this and test it, just feel free to send a pull request and I'll happily merge it!

thanks!

**Comment by Angel0ffDeath** [comment]
@neothematrix ok. will try to do this

**Comment by neothematrix** [comment]
fixed by #38
