### ISSUE TITLE
Problem installing in Ubuntu 20.04 / 22.04

### ISSUE THREAD

**Issue by jmb365** [neothematrix/noip-renew#41]
Hello neothematrix,

Firstly, I commend and thank you for forking the original and making it work again.  Wonderful work by loblab & you !

I ran into a minor issue running ./setup, which I was able to circumvent and thereafter I was able to successfully install & make it auto-renew the NOIP website record.

The problem:
> ./setup.sh
> No-IP Auto Renewal Script Setup.
> 1) Install/Repair Script	    3) Uninstall Script
> 2) Update noip.com account details  4) Exit setup.sh
> Select an option: 1
> Operating System: Ubuntu 22.04.1 LTS
> ./setup.sh.orig: line 34: install_debian: command not found

So in a nutshell here's what I did:
a) I saved your setup.sh as setup.sh.orig
b) Commented out the entire function install_debian()
c) Installed the google repo & keys using
> echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
> wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

d) Used 'sudo apt -y install ...' for the various packages install_debian() would have performed.
e) Then I ran the modified ./setup.sh

There may have been a better way to handle the problem I ran into, but this is what worked for me.  Running the setup.sh as 'sudo' or 'root' was not an option I wanted to pursue.
I wonder if you could:
1. modify your setup.sh to circumvent the problem I ran into?  OR
2. split the setup.sh into two parts where the first part is run under superuser privileges & the latter as normal user?

Your advice & comment(s) would be appreciated.  Thank you again for resurrecting & maintaining this code.

JMB

NOTE: Incidentally, the version I used is the latest, as I did a 'git clone ...' today.

**Comment by Angel0ffDeath** [comment]
./setup.sh.orig: line 34: install_debian: command not found

In general functions should be declared before they are called. In setup.sh this is not the case. While this works on raspbian it is possible not to work on other distributions.
I think only reordering the script will solve the problem

**Comment by Angel0ffDeath** [comment]
@jmb365 I suggest you to make the changes as per my previous comment, test it and if everything is ok, make PR
