### ISSUE TITLE
Is there a way to renew multiple accounts at once?

### ISSUE THREAD

**Issue by directentis1** [neothematrix/noip-renew#45]
Since I use many noip hostnames for many different purposes, 
I would like to ask if there is a way to automatically renew on multiple accounts?

**Comment by Angel0ffDeath** [comment]
You can  modify noip-renew-user.sh with for loop to cycle through all your accounts. Of course you need to add also credentials for all your accounts

**Comment by directentis1** [comment]
well, I wonder, can I use it with Github Actions to automatically update my noip.com hostnames?

**Comment by Angel0ffDeath** [comment]
@directentis1 Never tried it. I run the script via cron job on certain date

**Comment by Angel0ffDeath** [comment]
@directentis1 The only problem, if you cycle through all your accounts will be correct rescheduling of the script. So probably it will be better if you run the script separately for each account. This way script will be correctly rescheduled for this account

**Comment by directentis1** [comment]
@Angel0ffDeath I also plan to use crontab but the downside is that if you forget to turn on your computer at the time it happens, it will ignore and not notify you at all, so you need to put it on your server.

**Comment by Angel0ffDeath** [comment]
@directentis1 You are correct. Put it on server, NAS or whatever runs 24/7. Im using raspberry Pi 3 for my home auto ation and it runs non-stop
