### ISSUE TITLE
timeout???

### ISSUE THREAD

**Issue by drsurfer** [neothematrix/noip-renew#46]
After months, if not years, of honorable service on my RPi, I suddenly find this in the log:

```
[2024/01/11 12:29:06] - Debug level: 2
[2024/01/11 12:29:06] - Opening https://www.noip.com/login...
[2024/01/11 12:30:37] - Message: timeout: Timed out receiving message from renderer: 82.338
  (Session info: chrome-headless-shell=120.0.6099.102)
Stacktrace:
#0 0x000000ba9454 <unknown>
#1 0x00000087b1c8 <unknown>
#2 0x0000008614f0 <unknown>
#3 0x00000086135c <unknown>
#4 0x00000085f8ec <unknown>
#5 0x000000860244 <unknown>
#6 0x00000087011c <unknown>
#7 0x0000008880e8 <unknown>
#8 0x00000088d868 <unknown>
#9 0x000000860930 <unknown>
#10 0x000000887ee0 <unknown>
#11 0x000000914264 <unknown>
#12 0x0000008f5f64 <unknown>
#13 0x0000008ba73c <unknown>
#14 0x0000008bbdd0 <unknown>
#15 0x000000b732d4 <unknown>
#16 0x000000b77794 <unknown>
#17 0x000000b771c0 <unknown>
#18 0x000000b77bd4 <unknown>
#19 0x000000b603c0 <unknown>
#20 0x000000b77fe8 <unknown>
#21 0x000000b4951c <unknown>
#22 0x000000b97ff8 <unknown>
#23 0x000000b98144 <unknown>
#24 0x000000ba861c <unknown>
#25 0x000076f1f310 start_thread
#26 0x000000000000 <unknown>
```
The related exception.png image is a correct login page:
![image](https://github.com/neothematrix/noip-renew/assets/13066684/d236a575-e7ea-452a-9f4a-0eb5a99359cb)

Anyone have an idea what's going on?

**Comment by Angel0ffDeath** [comment]
@drsurfer Hmmm... I cannot reproduce this error. Everything works fine here. Did you updated chromium driver recently? Or selenium? If so, try to revert to previous version

**Comment by drsurfer** [comment]
I have no record of the updates, maybe something was updated by a usual raspbian update. 
I remember something about chromium recently, but I'm not sure. My home server is in "set it and forget it" mode :-)
Can you tell me the working version numbers for the chromium driver and selenium  on your system?

I'll try to increase the timeout, but I'm also convinced that it's useless. The really strange thing is that the exception saves a complete and correct image of the login page.

**Comment by Angel0ffDeath** [comment]
@drsurfer Mine are very old.... I'm running this on stretch... chromium-browser 72.0.3626.121-0 rpt4; selenium is 3.141.0

**Comment by Angel0ffDeath** [comment]
> I'll try to increase the timeout, but I'm also convinced that it's useless. The really strange thing is that the exception saves a complete and correct image of the login page.

Yes and it freezes at this point, which means that due to some reasons cannot find the correct fields Username and Password...

**Comment by Angel0ffDeath** [comment]
@drsurfer According to selenium documentation there is a little difference in commands.

Check this: https://www.selenium.dev/documentation/webdriver/troubleshooting/upgrade_to_selenium_4/
Especially findelement section. You can try to rewrite this part. Currently I can't test this. Must prepare test RPI with the latest rpi OS and latest chromium and selenium. I hope will have time to this during the weekend.

@neothematrix I know you use docker, but do you have any issues. Can you check please.

Can somebody else reproduce this error?

**Comment by neothematrix** [comment]
ciao,
no issues on my side either, I'm using docker as correctly pointed out by @Angel0ffDeath and chromium/chromedriver v99.0 so the old version is not an issue.
Perhaps I should find time to update the docker image :-)
Not sure what could be the issue with the timeout I also haven't touched the setup in a couple of years now.

**Comment by Angel0ffDeath** [comment]
@drsurfer @neothematrix Ok, I made some testst. I used RPi 4 with 4G RAM, debian bullseye - kernel version 6.1.21-v8+, python 3.9.2, chromium webbrowser 120.0.6099.102-rpt1.
The script works perfect with selenium version up to 4.10.0 including. The script doesn't work with selenium 4.11.0 and above. For these versions of selenium script should be rewritten, but I don't have right now time to read documentation. With selenium 4.11.0 the script even doesn't start

`Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/selenium_manager.py", line 73, in driver_location
    args = [str(self.get_binary()), "--browser", browser]
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/selenium_manager.py", line 57, in get_binary
    raise WebDriverException(f"Unable to obtain working Selenium Manager binary; {path}")
selenium.common.exceptions.WebDriverException: Message: Unable to obtain working Selenium Manager binary; /home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/linux/selenium-manager


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/noip-renew.py", line 232, in <module>
    sys.exit(main())
  File "/usr/local/bin/noip-renew.py", line 213, in main
    return (Robot(noip_username, noip_password, debug)).run()
  File "/usr/local/bin/noip-renew.py", line 52, in __init__
    self.browser = self.init_browser()
  File "/usr/local/bin/noip-renew.py", line 67, in init_browser
    browser = webdriver.Chrome(options=options)
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 51, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location`

With 4.10.0 everything is ok
`[2024/01/13 10:01:01] - Debug level: 2
[2024/01/13 10:01:01] - Opening https://www.noip.com/login...
[2024/01/13 10:01:05] - Logging in...
[2024/01/13 10:01:15] - Opening https://my.noip.com/dynamic-dns...
[2024/01/13 10:01:20] - xxxxxxxxxxx.ddns.net expires in 11 days
[2024/01/13 10:01:21] - Confirmed hosts: 0`


@drsurfer Try to update all your packages and kernel. Be sure selenium version is max 4.10.0. If necessary uninstall selenium with pip3 uninstall selenium and install required version with pip3 install selenium==4.10.0 (for instance)
Selenium 4.0.0 and above requires python version 3.7+. Selenium 4.10.0 requires python version 3.8+ 
Also try to run again setup.sh to install again (repair) the script.

**Comment by Angel0ffDeath** [comment]
@drsurfer Can you report what is current status by you?

**Comment by drsurfer** [comment]
> @drsurfer Can you report what is current status by you?

I've tried to upgrade selenium to 4.10.0, same results. 
I suspect there is something wrong with my Chromium installation. It's normal in a P3B+ it takes minutes to load itself, and it's so slow to be pratically unusable?
I will try to reinstall it as soon as I find some spare time.

**Comment by Angel0ffDeath** [comment]
@drsurfer yes, Im running it also on pi 3B and it takes a few minutes to confirm host, but who cares. On Pi4 is significantly faster

**Comment by drsurfer** [comment]
> @drsurfer yes, Im running it also on pi 3B and it takes a few minutes to confirm host, but who cares. On Pi4 is significantly faster Try to run setup.sh to repair instalation. Allow setup.sh to perform update

I think I solved it. I was running my pi with a 100MB swap file and it just wasn't enough for Chromium. I set it to 1GB and now Chromium is usable (-ish) and the script goes beyond the login page.
Then it stops because it doesn't find an element, but this is another story as I can see in the other [thread.](https://github.com/neothematrix/noip-renew/issues/47).
Thanks for the help.
```
[2024/01/19 07:56:11] - Debug level: 2
[2024/01/19 07:56:11] - Opening https://www.noip.com/login...
[2024/01/19 07:56:16] - Logging in...
[2024/01/19 07:56:26] - Opening https://my.noip.com/dynamic-dns...
[2024/01/19 07:56:33] - Message: no such element: Unable to locate element: {"method":"xpath","selector":".//following-sibling::td[4]/button[contains(@class, 'btn')]"}
```
