### ISSUE TITLE
Change in confirmation page

### ISSUE THREAD

**Issue by Angel0ffDeath** [neothematrix/noip-renew#47]
@neothematrix It looks like there is minor change in confirmation page. Today I received this error:

[2024/01/18 10:34:53] - Debug level: 2
[2024/01/18 10:34:53] - Opening https://www.noip.com/login...
[2024/01/18 10:35:03] - Logging in...
[2024/01/18 10:35:37] - Opening https://my.noip.com/dynamic-dns...
[2024/01/18 10:36:01] - Message: no such element: Unable to locate element: {"method":"xpath","selector":".//following-sibling::td[4]/button[contains(@class, 'btn')]"}

This is button Confirm.
Line 183 in noip-renew.py (current):
return host.find_element(By.XPATH, ".//following-sibling::td[4]/button[contains(@class, 'btn')]")

Changing this line to:
return host.find_element(By.XPATH, "//td[6]/button[contains(@class, 'btn-success')]")

Fixes the issue.
EDIT: atclass should be with small letter, but obviously github interprets it as username.... Please update the code.

**Comment by drsurfer** [comment]
This will not work if the host is already confirmed and only a "Modify" and "X" (remove) buttons are shown. I've no time now to fix the code, may be next week, if someone doesn't come up with a more general solution.

PS: `@class` will remain lowercase if you use code quoting.

**Comment by neothematrix** [comment]
yep I have the same issue as @drsurfer  now, I'll check your fixes asap and publish a new version, I'll take time to also accept your previous PR, thank you all for contributing!

**Comment by Angel0ffDeath** [comment]
> yep I have the same issue as @drsurfer now, I'll check your fixes asap and publish a new version, I'll take time to also accept your previous PR, thank you all for contributing!

Few years ago, when you started this fork, I promised you full support to keep the code working. Just fulfilling my promises. No need to thank me :)

**Comment by Angel0ffDeath** [comment]
@neothematrix Btw it is a good idea, all these strings we are searching for, to be defined in the beginning of the script. Will be easier to modify them without searching all the code.

**Comment by neothematrix** [comment]
thank you both @Angel0ffDeath  and @drsurfer, I've just pushed a new version that includes the fix, I've tested it on both scnearios, 1 host to confirm and no hosts to confirm and I have 3 hosts on my account so this works properly!
I'll soon push a new version of the docker image too.
again thank you a lot for your collaboration here!
