### ISSUE TITLE
Update readme and selenium 4.11.0 suggestion

### ISSUE THREAD

**Issue by Angel0ffDeath** [neothematrix/noip-renew#50]
@neothematrix I updated readme.md with chrome and selenium working versions. Please merge this.

Also, if you want you can make a new branch of the code which will work with selenium 4.11.0 and above. Python script should be reworked for the new commands, but I dont want to mess the old code, since most of the people here are using it as it is. This one is not urgent. Im still reading documentation.... For now it looks like only 'options' are changed, but I dont know what will come next...
The other option is setup.sh to detect which selenium version is installed and to aleter python script - something like my implementation of running the script of python 3.5
However this will take some time, since not so much free time for me right now. Help will be appreciated :)

**Comment by neothematrix** [comment]
ciao,
PR merged and thanks for the comments.
I see if I can work on making the script compatible with selenium 4.11 but not sure how much time I can dedicate on it.
thanks!

**Comment by Angel0ffDeath** [comment]
@neothematrix Yep.... Understanding. Not so much free time here also. From selenium docs I understand browser options are now service and probably this is the only issue, but cannot be sure without testing :) . Will try to test it next weekend, if boss (understand wife) doesn't have some other ideas...

**Comment by Angel0ffDeath** [comment]
@neothematrix I performed clean installation of the script. Then installed selenium 4.11.0. The script is working. Then I installed selenium 4.17.2. The script is working.
It looks something happened with the previous installation.
Will close this issue and will update readme.md again
