### ISSUE TITLE
No-IP implemented ReCaptcha

### ISSUE THREAD

**Issue by LaiKash** [neothematrix/noip-renew#58]
As the tittle says, it's just to bring out that they implemented ReCaptcha so the script might not work as expected. For now they are using ReCaptcha v2 that "could be bypassed" with Selenium but if they implement ReCaptcha v3 it could bring issues. I don't know if it is worth the effort (having Duck DNS available...). Maybe just of we want to keep it with compatible routers.

**Comment by neothematrix** [comment]
ciao @LaiKash 
where do you see the captcha? during login? or during host verification?
If it's during login, I don't see it at the moment, but I know that no-ip sometimes show you the captcha temporarily if you perform too many attempts in a short time.

**Comment by mitzone** [comment]
this happens if you do a lot of login tries in a short period of time.

**Comment by Angel0ffDeath** [comment]
@neothematrix @LaiKash @mitzone  Yep. Agreed. I tried it. I cycled the script to execute permanently. On my RPi 3B+ loging and hosts check/confirmation takes about 2 min. ReCaptcha appeared after 12th attempt. There is cooling time - I don't know how much exactly but after about 6 hours there was no more ReCaptcha.
@LaiKash I don't know what exactly you were trying to do, but whatever it is, it is not necessary to try to logon so often to the site.

**Comment by LaiKash** [comment]
> @neothematrix @LaiKash @mitzone Yep. Agreed. I tried it. I cycled the script to execute permanently. On my RPi 3B+ loging and hosts check/confirmation takes about 2 min. ReCaptcha appeared after 12th attempt. There is cooling time - I don't know how much exactly but after about 6 hours there was no more ReCaptcha. @LaiKash I don't know what exactly you were trying to do, but whatever it is, it is not necessary to try to logon so often to the site.

Actually it's not during the login, it's in the screen to accept the renovation of the domain for another 30d. I'm not running the script often, I think it's onces per month (I'll check it). I'm gonna turn of the script to renovate it manually and check, it could also be associated to my IP. I'll keep you posted, thanks!

**Comment by Angel0ffDeath** [comment]
@LaiKash Strange, by me occurred at login. Can you post some of debug.png files showing when exactly this occurs?

**Comment by LaiKash** [comment]
> @LaiKash Strange, by me occurred at login. Can you post some of debug.png files showing when exactly this occurs?
> 
> EDIT: Can you confirm after few hours not login in, there is still captcha. I can add captcha2 solver to the script (yes you are correct - captcha2 can be solved, I use it in some other apps, I wrote), but it seems only you (currently) have this issue. Can somebody else confirm or complain?

Today was my DDNS renovation day, here is the captcha (from https[:]//www.noip.com/es-MX/confirm-host):

![image](https://github.com/neothematrix/noip-renew/assets/24409595/8aa5da69-a5b9-4b55-baa2-67b2d8eb7127)

I have tried with a VPN to different countries, as well as with different (completely clean) non-Chrome based browsers with the same result. It could be because of the "es-MX" part or because my account (I would say my domain as you don't need to be logged in to use the the renovation link ) is already red flagged for them. 

No need to implement a captcha solver just for me as I have other DDNS providers pointing to my IP already but I'm happy to help if it is useful @Angel0ffDeath 
My domain is expired now but I should have some weeks to renovate it to do some tests. Quick tip: if you don't renovate a free hostname are deleted and temporarily blocked from creation (so you cannot create the same hostname anymore, need to contact support...)

**Comment by neothematrix** [comment]
@LaiKash thanks for the update, if you click on the renovate link on the email it's totally normal to see the captcha. If you open noip.com , login, navigate to your dynamic hosts and then click the renew link there, you should encounter no captcha, this is exactly what this script does
