### ISSUE TITLE
ModuleNotFoundError: No module named 'pyotp'

### ISSUE THREAD

**Issue by fana13** [neothematrix/noip-renew#62]
Hi guys, i've updated script to v2.0.0 OS Debian 11
I've this issue when i start the script : 
File "/usr/local/bin/noip-renew.py", line 24, in <module>
    from pyotp import *
ModuleNotFoundError: No module named 'pyotp'

Module pyotp is already satisfied : 
Requirement already satisfied: pyotp in /usr/local/lib/python3.11/site-packages (2.9.0)

Did you have any ideas ?
Thanks.

**Comment by ray1025** [comment]
pip install pyotp

**Comment by fana13** [comment]
pytop is already installed

**Comment by neothematrix** [comment]
strange, is this a regular Debian 11 or raspbian or something similar? If you give me some more details I can try and reproduce the error

**Comment by fana13** [comment]
I didn't know why, but i must have to install specific python version using this command : 
python3.10 -m pip install pyotp
